# install.packages('httr')
install.packages('devtools')
# install.packages('tensorflow')
# install.packages("BiocManager")
# install.packages('Seurat')
# BiocManager::install("scran")
# BiocManager::install("scater")
# BiocManager::install("SingleCellExperiment")
# BiocManager::install("EnsDb.Hsapiens.v86")
devtools::install_github("Irrationone/cellassign")
devtools::install_github("kieranrcampbell/clonealign")
