#!/bin/bash
export PYTHONPATH=$PYTHONPATH:/codebase/scrna-pipeline/
python3 /codebase/scrna-pipeline/generate_config.py --jobpath $(pwd) integrate $*
python3 /codebase/scrna-pipeline/pipeline_integration.py --submit local --maxjobs 4
