#!/bin/bash
cd runs
export R_HOME=/usr/local/lib/R/
export LD_LIBRARY_PATH=/usr/local/lib/R/lib/
bash /codebase/cellranger-3.0.2/sourceme.bash
export PYTHONPATH=$PYTHONPATH:/codebase/SCRNApipeline/
export PATH=$PATH:/common/juno/OS7/10.1/linux3.10-glibc2.17-x86_64/bin
python3 /codebase/SCRNApipeline/generate_config.py --cellranger /codebase/cellranger-3.0.2/cellranger-cs/3.0.2/bin/ --lsf $*
python3 /codebase/SCRNApipeline/pipeline_basic.py --submit local
